//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DacsOnline.Model.DACSArtistSearchWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DACSAtristList", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DACSAtristList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DacsOnline.Model.DACSArtistSearchWebService.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DacsOnline.Model.DACSArtistSearchWebService.DACSArtist[] ArtistListField;
        
        private int TotalArtistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public DacsOnline.Model.DACSArtistSearchWebService.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public DacsOnline.Model.DACSArtistSearchWebService.DACSArtist[] ArtistList {
            get {
                return this.ArtistListField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistListField, value) != true)) {
                    this.ArtistListField = value;
                    this.RaisePropertyChanged("ArtistList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int TotalArtist {
            get {
                return this.TotalArtistField;
            }
            set {
                if ((this.TotalArtistField.Equals(value) != true)) {
                    this.TotalArtistField = value;
                    this.RaisePropertyChanged("TotalArtist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DACSArtist", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DACSArtist : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DacsOnline.Model.DACSArtistSearchWebService.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARRConfirmedNationalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARRMembershipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ArtistIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticFirstNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthenticLastNameField;
        
        private bool CLFullConsultationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLMemebershipTypeField;
        
        private bool CLRightsAuctionHouseOnlyField;
        
        private bool CLRightsExcludingMerchandiseField;
        
        private bool CLRightsExcludingMultimediaField;
        
        private bool CLRightsMultimediaOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        private bool ImageHireField;
        
        private bool InCopyrightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nationality1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nationality2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nationality3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nationality4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pseudonym_1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pseudonym_2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pseudonym_3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pseudonym_4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pseudonym_5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Pseudonym_6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearOfDeathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public DacsOnline.Model.DACSArtistSearchWebService.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ARRConfirmedNationality {
            get {
                return this.ARRConfirmedNationalityField;
            }
            set {
                if ((object.ReferenceEquals(this.ARRConfirmedNationalityField, value) != true)) {
                    this.ARRConfirmedNationalityField = value;
                    this.RaisePropertyChanged("ARRConfirmedNationality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ARRMembership {
            get {
                return this.ARRMembershipField;
            }
            set {
                if ((object.ReferenceEquals(this.ARRMembershipField, value) != true)) {
                    this.ARRMembershipField = value;
                    this.RaisePropertyChanged("ARRMembership");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ArtistId {
            get {
                return this.ArtistIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ArtistIdField, value) != true)) {
                    this.ArtistIdField = value;
                    this.RaisePropertyChanged("ArtistId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AuthenticFirstNames {
            get {
                return this.AuthenticFirstNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticFirstNamesField, value) != true)) {
                    this.AuthenticFirstNamesField = value;
                    this.RaisePropertyChanged("AuthenticFirstNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AuthenticLastName {
            get {
                return this.AuthenticLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthenticLastNameField, value) != true)) {
                    this.AuthenticLastNameField = value;
                    this.RaisePropertyChanged("AuthenticLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public bool CLFullConsultation {
            get {
                return this.CLFullConsultationField;
            }
            set {
                if ((this.CLFullConsultationField.Equals(value) != true)) {
                    this.CLFullConsultationField = value;
                    this.RaisePropertyChanged("CLFullConsultation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CLMemebershipType {
            get {
                return this.CLMemebershipTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CLMemebershipTypeField, value) != true)) {
                    this.CLMemebershipTypeField = value;
                    this.RaisePropertyChanged("CLMemebershipType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool CLRightsAuctionHouseOnly {
            get {
                return this.CLRightsAuctionHouseOnlyField;
            }
            set {
                if ((this.CLRightsAuctionHouseOnlyField.Equals(value) != true)) {
                    this.CLRightsAuctionHouseOnlyField = value;
                    this.RaisePropertyChanged("CLRightsAuctionHouseOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public bool CLRightsExcludingMerchandise {
            get {
                return this.CLRightsExcludingMerchandiseField;
            }
            set {
                if ((this.CLRightsExcludingMerchandiseField.Equals(value) != true)) {
                    this.CLRightsExcludingMerchandiseField = value;
                    this.RaisePropertyChanged("CLRightsExcludingMerchandise");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool CLRightsExcludingMultimedia {
            get {
                return this.CLRightsExcludingMultimediaField;
            }
            set {
                if ((this.CLRightsExcludingMultimediaField.Equals(value) != true)) {
                    this.CLRightsExcludingMultimediaField = value;
                    this.RaisePropertyChanged("CLRightsExcludingMultimedia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool CLRightsMultimediaOnly {
            get {
                return this.CLRightsMultimediaOnlyField;
            }
            set {
                if ((this.CLRightsMultimediaOnlyField.Equals(value) != true)) {
                    this.CLRightsMultimediaOnlyField = value;
                    this.RaisePropertyChanged("CLRightsMultimediaOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public bool ImageHire {
            get {
                return this.ImageHireField;
            }
            set {
                if ((this.ImageHireField.Equals(value) != true)) {
                    this.ImageHireField = value;
                    this.RaisePropertyChanged("ImageHire");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public bool InCopyright {
            get {
                return this.InCopyrightField;
            }
            set {
                if ((this.InCopyrightField.Equals(value) != true)) {
                    this.InCopyrightField = value;
                    this.RaisePropertyChanged("InCopyright");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string Nationality1 {
            get {
                return this.Nationality1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nationality1Field, value) != true)) {
                    this.Nationality1Field = value;
                    this.RaisePropertyChanged("Nationality1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string Nationality2 {
            get {
                return this.Nationality2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nationality2Field, value) != true)) {
                    this.Nationality2Field = value;
                    this.RaisePropertyChanged("Nationality2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public string Nationality3 {
            get {
                return this.Nationality3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nationality3Field, value) != true)) {
                    this.Nationality3Field = value;
                    this.RaisePropertyChanged("Nationality3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=19)]
        public string Nationality4 {
            get {
                return this.Nationality4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Nationality4Field, value) != true)) {
                    this.Nationality4Field = value;
                    this.RaisePropertyChanged("Nationality4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Pseudonym_1 {
            get {
                return this.Pseudonym_1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pseudonym_1Field, value) != true)) {
                    this.Pseudonym_1Field = value;
                    this.RaisePropertyChanged("Pseudonym_1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=21)]
        public string Pseudonym_2 {
            get {
                return this.Pseudonym_2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pseudonym_2Field, value) != true)) {
                    this.Pseudonym_2Field = value;
                    this.RaisePropertyChanged("Pseudonym_2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=22)]
        public string Pseudonym_3 {
            get {
                return this.Pseudonym_3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pseudonym_3Field, value) != true)) {
                    this.Pseudonym_3Field = value;
                    this.RaisePropertyChanged("Pseudonym_3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string Pseudonym_4 {
            get {
                return this.Pseudonym_4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pseudonym_4Field, value) != true)) {
                    this.Pseudonym_4Field = value;
                    this.RaisePropertyChanged("Pseudonym_4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=24)]
        public string Pseudonym_5 {
            get {
                return this.Pseudonym_5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pseudonym_5Field, value) != true)) {
                    this.Pseudonym_5Field = value;
                    this.RaisePropertyChanged("Pseudonym_5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string Pseudonym_6 {
            get {
                return this.Pseudonym_6Field;
            }
            set {
                if ((object.ReferenceEquals(this.Pseudonym_6Field, value) != true)) {
                    this.Pseudonym_6Field = value;
                    this.RaisePropertyChanged("Pseudonym_6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=26)]
        public string YearOfBirth {
            get {
                return this.YearOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.YearOfBirthField, value) != true)) {
                    this.YearOfBirthField = value;
                    this.RaisePropertyChanged("YearOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string YearOfDeath {
            get {
                return this.YearOfDeathField;
            }
            set {
                if ((object.ReferenceEquals(this.YearOfDeathField, value) != true)) {
                    this.YearOfDeathField = value;
                    this.RaisePropertyChanged("YearOfDeath");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DACSArtistSearchWebService.DACSAccessSoap")]
    public interface DACSAccessSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        DacsOnline.Model.DACSArtistSearchWebService.HelloWorldResponse HelloWorld(DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchARRArtist", ReplyAction="*")]
        DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistResponse SearchARRArtist(DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchAllArtist", ReplyAction="*")]
        DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistResponse SearchAllArtist(DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequest request);
        
        // CODEGEN: Generating message contract since element name SearchArtistDetailResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchArtistDetail", ReplyAction="*")]
        DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailResponse SearchArtistDetail(DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(DacsOnline.Model.DACSArtistSearchWebService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchARRArtistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchARRArtist", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequestBody Body;
        
        public SearchARRArtistRequest() {
        }
        
        public SearchARRArtistRequest(DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchARRArtistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ArtistFirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ArtistLastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pageNo;
        
        public SearchARRArtistRequestBody() {
        }
        
        public SearchARRArtistRequestBody(string key, string ArtistFirstName, string ArtistLastName, int pageSize, int pageNo) {
            this.key = key;
            this.ArtistFirstName = ArtistFirstName;
            this.ArtistLastName = ArtistLastName;
            this.pageSize = pageSize;
            this.pageNo = pageNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchARRArtistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchARRArtistResponse", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistResponseBody Body;
        
        public SearchARRArtistResponse() {
        }
        
        public SearchARRArtistResponse(DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchARRArtistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.DACSAtristList SearchARRArtistResult;
        
        public SearchARRArtistResponseBody() {
        }
        
        public SearchARRArtistResponseBody(DacsOnline.Model.DACSArtistSearchWebService.DACSAtristList SearchARRArtistResult) {
            this.SearchARRArtistResult = SearchARRArtistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchAllArtistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchAllArtist", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequestBody Body;
        
        public SearchAllArtistRequest() {
        }
        
        public SearchAllArtistRequest(DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchAllArtistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ArtistFirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ArtistLastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pageNo;
        
        public SearchAllArtistRequestBody() {
        }
        
        public SearchAllArtistRequestBody(string key, string ArtistFirstName, string ArtistLastName, int pageSize, int pageNo) {
            this.key = key;
            this.ArtistFirstName = ArtistFirstName;
            this.ArtistLastName = ArtistLastName;
            this.pageSize = pageSize;
            this.pageNo = pageNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchAllArtistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchAllArtistResponse", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistResponseBody Body;
        
        public SearchAllArtistResponse() {
        }
        
        public SearchAllArtistResponse(DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchAllArtistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.DACSAtristList SearchAllArtistResult;
        
        public SearchAllArtistResponseBody() {
        }
        
        public SearchAllArtistResponseBody(DacsOnline.Model.DACSArtistSearchWebService.DACSAtristList SearchAllArtistResult) {
            this.SearchAllArtistResult = SearchAllArtistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchArtistDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchArtistDetail", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequestBody Body;
        
        public SearchArtistDetailRequest() {
        }
        
        public SearchArtistDetailRequest(DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchArtistDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Guid id;
        
        public SearchArtistDetailRequestBody() {
        }
        
        public SearchArtistDetailRequestBody(System.Guid id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchArtistDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchArtistDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailResponseBody Body;
        
        public SearchArtistDetailResponse() {
        }
        
        public SearchArtistDetailResponse(DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchArtistDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DacsOnline.Model.DACSArtistSearchWebService.DACSArtist SearchArtistDetailResult;
        
        public SearchArtistDetailResponseBody() {
        }
        
        public SearchArtistDetailResponseBody(DacsOnline.Model.DACSArtistSearchWebService.DACSArtist SearchArtistDetailResult) {
            this.SearchArtistDetailResult = SearchArtistDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DACSAccessSoapChannel : DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DACSAccessSoapClient : System.ServiceModel.ClientBase<DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap>, DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap {
        
        public DACSAccessSoapClient() {
        }
        
        public DACSAccessSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DACSAccessSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DACSAccessSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DACSAccessSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DacsOnline.Model.DACSArtistSearchWebService.HelloWorldResponse DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap.HelloWorld(DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequest inValue = new DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequest();
            inValue.Body = new DacsOnline.Model.DACSArtistSearchWebService.HelloWorldRequestBody();
            DacsOnline.Model.DACSArtistSearchWebService.HelloWorldResponse retVal = ((DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistResponse DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap.SearchARRArtist(DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequest request) {
            return base.Channel.SearchARRArtist(request);
        }
        
        public DacsOnline.Model.DACSArtistSearchWebService.DACSAtristList SearchARRArtist(string key, string ArtistFirstName, string ArtistLastName, int pageSize, int pageNo) {
            DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequest inValue = new DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequest();
            inValue.Body = new DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistRequestBody();
            inValue.Body.key = key;
            inValue.Body.ArtistFirstName = ArtistFirstName;
            inValue.Body.ArtistLastName = ArtistLastName;
            inValue.Body.pageSize = pageSize;
            inValue.Body.pageNo = pageNo;
            DacsOnline.Model.DACSArtistSearchWebService.SearchARRArtistResponse retVal = ((DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap)(this)).SearchARRArtist(inValue);
            return retVal.Body.SearchARRArtistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistResponse DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap.SearchAllArtist(DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequest request) {
            return base.Channel.SearchAllArtist(request);
        }
        
        public DacsOnline.Model.DACSArtistSearchWebService.DACSAtristList SearchAllArtist(string key, string ArtistFirstName, string ArtistLastName, int pageSize, int pageNo) {
            DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequest inValue = new DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequest();
            inValue.Body = new DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistRequestBody();
            inValue.Body.key = key;
            inValue.Body.ArtistFirstName = ArtistFirstName;
            inValue.Body.ArtistLastName = ArtistLastName;
            inValue.Body.pageSize = pageSize;
            inValue.Body.pageNo = pageNo;
            DacsOnline.Model.DACSArtistSearchWebService.SearchAllArtistResponse retVal = ((DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap)(this)).SearchAllArtist(inValue);
            return retVal.Body.SearchAllArtistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailResponse DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap.SearchArtistDetail(DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequest request) {
            return base.Channel.SearchArtistDetail(request);
        }
        
        public DacsOnline.Model.DACSArtistSearchWebService.DACSArtist SearchArtistDetail(System.Guid id) {
            DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequest inValue = new DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequest();
            inValue.Body = new DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailRequestBody();
            inValue.Body.id = id;
            DacsOnline.Model.DACSArtistSearchWebService.SearchArtistDetailResponse retVal = ((DacsOnline.Model.DACSArtistSearchWebService.DACSAccessSoap)(this)).SearchArtistDetail(inValue);
            return retVal.Body.SearchArtistDetailResult;
        }
    }
}
